//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woland.Tests {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobServeData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal JobServeData() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woland.Tests.JobServeData", typeof(JobServeData).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;IT Business/Solutions Analyst - London - &amp;#163;400 - 500 p/day - London - 01/07/2016 22:17:25&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/search-jobs-in-London,-London,-United-Kingdom/IT-BUSINESS-SOLUTIONS-ANALYST-LONDON-400-500-P-DAY-3842279F367B28C9/&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;appl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JobLead1 {
            get {
                return ResourceManager.GetString("JobLead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Technical Lead Developer - Cognos - London, Greater London, England - 01/07/2016 20:10:02&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/search-jobs-in-London,-London,-United-Kingdom/TECHNICAL-LEAD-DEVELOPER-COGNOS-F5C2D146F3690E1C/&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precompose [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JobLead2 {
            get {
                return ResourceManager.GetString("JobLead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Application Security Analyst (Security Developer) - London - 01/07/2016 18:46:57&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/search-jobs-in-London,-London,-United-Kingdom/APPLICATION-SECURITY-ANALYST-SECURITY-DEVELOPER-FF2CC047F505C68D/&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-pre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JobLead3 {
            get {
                return ResourceManager.GetString("JobLead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;JobServe - Find your next job&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/JobListing.aspx?shid=37B6233495B9238815&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link href=&quot;/favicon.ico&quot; rel=&quot;shortcut ico [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MainResponse {
            get {
                return ResourceManager.GetString("MainResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;JobServe - Find your next job&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/JobListing.aspx?shid=37B6233495B9238815&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link href=&quot;/favicon.ico&quot; rel=&quot;shortcut ico [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResultPage2 {
            get {
                return ResourceManager.GetString("ResultPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;JobServe - Find your next job&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/JobListing.aspx?shid=37B6233495B9238815&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link href=&quot;/favicon.ico&quot; rel=&quot;shortcut ico [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResultPage3 {
            get {
                return ResourceManager.GetString("ResultPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;JobServe - Find your next job&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/JobListing.aspx?shid=37B6233495B9238815&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link href=&quot;/favicon.ico&quot; rel=&quot;shortcut ico [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResultPage4 {
            get {
                return ResourceManager.GetString("ResultPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;JobServe - Find your next job&lt;/title&gt;
        ///	
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///	&lt;link rel=&quot;canonical&quot; href=&quot;/gb/en/JobListing.aspx?shid=37B6233495B9238815&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://az274887.vo.msecnd.net/images/apple-touch-icon.png&quot; /&gt;
        ///	&lt;link href=&quot;/favicon.ico&quot; rel=&quot;shortcut ico [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResultPage5 {
            get {
                return ResourceManager.GetString("ResultPage5", resourceCulture);
            }
        }
    }
}
